#!/bin/bash

if [ $(id -u) -eq 0 ]; then
    read -p "Enter username : " username
    userdel -r $username
    groupdel $username
    rm -rf /nfsfile/dell/$username
else
    echo "Only root may add a user to the system."
    exit 2
fi
